javafx:
  title: Communication Client
  #  appicons:
  stage:
    width: 650
    height:
    resizable:
    sytle:

path:
  rec: src\main\resources\rec\rec.txt
  start: src\main\resources\start\start.yml
  task: src\main\resources\task\task.yml

heartbeat:
  time-interval: 5000
  time-out: 15000
  time-retry: 1000

#spring 默认单线程执行定时任务，必须配置线程池，否则会踩坑
spring:
  task:
    scheduling:
      pool:
        size: 10